# Generated by Django 5.1.3 on 2024-12-06 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_alter_product_sizes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='sizes',
            field=models.CharField(blank=True, default='', help_text='Comma-separated sizes (XS,S,M,L,XL)', max_length=100),
        ),
    ]
